local palette = require("hex_steel.palette")
local config = require("hex_steel.config")

local M = {}

local function extend(base, extra)
  return vim.tbl_extend("force", base or {}, extra or {})
end

-- Helix stores styling as a list of modifiers. Convert those to Neovim's
-- highlight attributes so we can keep a single mapping source of truth.
local function with_style(spec, modifiers)
  local out = vim.deepcopy(spec)
  for _, modifier in ipairs(modifiers or {}) do
    if modifier == "bold" then
      out.bold = true
    elseif modifier == "italic" then
      out.italic = true
    elseif modifier == "underlined" then
      out.underline = true
    elseif modifier == "crossed_out" then
      out.strikethrough = true
    end
  end
  return out
end

local function bg(color, transparent)
  if transparent then
    return "NONE"
  end
  return color
end

-- This table mirrors the semantic buckets from the Helix theme before they are
-- expanded into Neovim/Vim/Tree-sitter/LSP highlight group names.
local function helix_groups()
  local p = palette
  local transparent = config.options.transparent

  return {
    comment = { fg = p.comment },
    comment_doc = with_style({ bg = p.comment_doc }, { "italic" }),

    constant = { fg = p.t11 },
    func = { fg = p.t10 },
    method = { fg = p.t7 },
    func_macro = { fg = p.t7 },
    storage_modifier = { fg = p.t7 },
    control_import = { fg = p.t8 },
    control = { fg = p.t8 },
    keyword_function = { fg = p.t11 },
    keyword = { fg = p.t6 },
    operator = { fg = p.t8 },
    punctuation = { fg = p.t9 },
    string = with_style({ fg = p.t6 }, { "italic" }),
    regexp = { fg = p.t6 },
    tag = { fg = p.t4 },
    type = with_style({ fg = p.t8 }, { "bold" }),
    namespace = with_style({ fg = p.t6 }, { "bold" }),
    variable = { fg = p.t4 },
    parameter = { fg = p.t6 },
    member = { fg = p.t3 },
    label = { fg = p.t4 },

    diff_add = { fg = p.diff_plus },
    diff_change = { fg = p.diff_delta },
    diff_text = { fg = p.diff_delta_moved },
    diff_delete = { fg = p.diff_minus },

    cursor_insert = { fg = p.t2, bg = p.highlight },
    cursor_select = { fg = p.t2, bg = p.highlight_two },
    cursor_normal = { fg = p.t1, bg = p.highlight_three },
    cursor_match = { fg = p.highlight, bg = p.t1, bold = true },
    cursorline = { bg = bg(p.ruler, transparent) },

    line_nr = { fg = p.t3, bg = bg(p.t2, transparent) },
    line_nr_selected = { fg = p.highlight_three, bg = bg(p.t2, transparent) },
    gutter = { bg = bg(p.t2, transparent) },

    background = { fg = p.t4, bg = bg(p.t2, transparent) },
    separator = { fg = p.t3 },
    help = { fg = p.t4, bg = bg(p.t1, transparent) },
    menu = { fg = p.t4, bg = bg(p.t1, transparent) },
    menu_selected = { fg = p.highlight_three, bg = bg(p.t1, transparent) },
    popup = { fg = p.t4, bg = bg(p.t1, transparent) },
    window = { fg = p.t4 },

    selection = { fg = p.selection_fg, bg = p.selection },

    statusline = { fg = p.t4, bg = bg(p.t1, transparent) },
    statusline_inactive = { fg = p.t4, bg = bg(p.t1, transparent) },
    statusline_normal = { fg = p.t3, bg = bg(p.t1, transparent) },
    statusline_insert = { fg = p.t3, bg = bg(p.t1, transparent) },
    statusline_select = { fg = p.highlight, bg = bg(p.t4, transparent) },

    text = { fg = p.t4 },
    text_focus = { fg = p.highlight_three, bold = true },

    ruler = { bg = bg(p.ruler, transparent) },
    indent_guide = { fg = p.t3 },
    whitespace = { fg = p.t3 },
    jump_label = { fg = p.t11, bold = true },
    inlay_hint = { fg = p.hints, bold = true },

    bufferline = { fg = p.t3, bg = bg(p.t1, transparent) },
    bufferline_active = { fg = p.t7, bg = bg(p.t2, transparent) },

    diagnostic_error = { undercurl = true, sp = p.error },
    diagnostic_warning = { undercurl = true, sp = p.warning },
    diagnostic_info = { undercurl = true, sp = p.info },
    diagnostic_hint = { undercurl = true, sp = p.display },

    error = with_style({ fg = p.error }, { "bold" }),
    warning = with_style({ fg = p.warning }, { "bold" }),
    info = with_style({ fg = p.info }, { "bold" }),
    hint = with_style({ fg = p.display }, { "bold" }),
    special = with_style({ fg = p.t7 }, { "bold" }),

    heading = { fg = p.t7 },
    list = { fg = p.t7 },
    markup = { fg = p.t4 },
    strikethrough = with_style({ fg = p.t4 }, { "crossed_out" }),
    link_url = with_style({ fg = p.t11 }, { "underlined" }),
    link_text = { fg = p.t11 },
    quote = { fg = p.t5 },
    raw = { fg = p.t4 },
  }
end

function M.groups()
  local h = helix_groups()
  local p = palette
  local transparent = config.options.transparent

  return {
    -- Core editor UI
    Normal = h.background,
    NormalNC = h.background,
    NormalFloat = h.popup,
    FloatBorder = extend(h.window, { bg = bg(p.t1, transparent) }),
    FloatTitle = h.text_focus,
    ColorColumn = h.ruler,
    Conceal = { fg = p.t5 },
    Cursor = h.cursor_normal,
    lCursor = h.cursor_insert,
    CursorIM = h.cursor_insert,
    TermCursor = h.cursor_normal,
    TermCursorNC = h.cursor_normal,
    CursorLine = h.cursorline,
    CursorColumn = h.cursorline,
    CursorLineNr = h.line_nr_selected,
    LineNr = h.line_nr,
    SignColumn = h.gutter,
    FoldColumn = h.gutter,
    CursorLineFold = h.line_nr_selected,
    CursorLineSign = h.line_nr_selected,
    Directory = h.text_focus,
    DiffAdd = h.diff_add,
    DiffChange = h.diff_change,
    DiffDelete = h.diff_delete,
    DiffText = h.diff_text,
    EndOfBuffer = { fg = p.t2, bg = bg(p.t2, transparent) },
    ErrorMsg = h.error,
    VertSplit = h.separator,
    WinSeparator = h.separator,
    Folded = extend(h.comment, { bg = bg(p.t1, transparent) }),
    IncSearch = { fg = p.t2, bg = p.highlight },
    CurSearch = { fg = p.t2, bg = p.highlight_two },
    Search = { fg = p.selection_fg, bg = p.selection },
    Substitute = { fg = p.t1, bg = p.highlight_three, bold = true },
    MatchParen = h.cursor_match,
    ModeMsg = h.text_focus,
    MoreMsg = h.info,
    NonText = h.whitespace,
    Whitespace = h.whitespace,
    SpecialKey = h.whitespace,
    Pmenu = h.menu,
    PmenuSel = h.menu_selected,
    PmenuSbar = { bg = bg(p.t2, transparent) },
    PmenuThumb = { bg = bg(p.t3, transparent) },
    Question = h.info,
    QuickFixLine = { fg = p.selection_fg, bg = p.selection, bold = true },
    SpellBad = { undercurl = true, sp = p.error },
    SpellCap = { undercurl = true, sp = p.display },
    SpellLocal = { undercurl = true, sp = p.info },
    SpellRare = { undercurl = true, sp = p.warning },
    StatusLine = { fg = p.t10, bg = bg(p.ruler, transparent) },
    StatusLineNC = { fg = p.t5, bg = bg(p.t2, transparent) },
    StatusLineTerm = { fg = p.t10, bg = bg(p.ruler, transparent) },
    StatusLineTermNC = { fg = p.t5, bg = bg(p.t2, transparent) },
    TabLine = h.bufferline,
    TabLineFill = { bg = bg(p.t1, transparent) },
    TabLineSel = h.bufferline_active,
    Title = h.text_focus,
    Visual = h.selection,
    VisualNOS = h.selection,
    WarningMsg = h.warning,
    WildMenu = h.menu_selected,
    WinBar = { fg = p.t10, bg = bg(p.ruler, transparent) },
    WinBarNC = { fg = p.t5, bg = bg(p.t2, transparent) },
    MsgArea = { fg = p.t10, bg = bg(p.ruler, transparent) },
    MsgSeparator = h.separator,
    HexSteelStatuslineFill = { fg = p.t10, bg = bg(p.ruler, transparent) },
    HexSteelStatuslineInactive = { fg = p.t5, bg = bg(p.t2, transparent) },
    HexSteelStatuslineFile = { fg = p.t10, bg = bg(p.ruler, transparent), bold = true },
    HexSteelStatuslineInfo = { fg = p.t5, bg = bg(p.ruler, transparent) },
    HexSteelStatuslineGit = { fg = p.t8, bg = bg(p.ruler, transparent), bold = true },
    HexSteelStatuslineModeNormal = { fg = p.t1, bg = p.highlight_three, bold = true },
    HexSteelStatuslineModeInsert = { fg = p.t2, bg = p.highlight, bold = true },
    HexSteelStatuslineModeVisual = { fg = p.t2, bg = p.highlight_two, bold = true },
    HexSteelStatuslineModeReplace = { fg = p.t2, bg = p.t7, bold = true },
    HexSteelStatuslineModeCommand = { fg = p.t1, bg = p.t11, bold = true },
    HexSteelStatuslineModeOther = { fg = p.t1, bg = p.t8, bold = true },

    -- Legacy Vim syntax groups
    Comment = h.comment,
    SpecialComment = h.comment_doc,
    Constant = h.constant,
    String = h.string,
    Character = h.string,
    Number = h.constant,
    Boolean = h.constant,
    Float = h.constant,
    Identifier = h.variable,
    Function = h.func,
    Statement = h.control,
    Conditional = h.control,
    Repeat = h.control,
    Label = h.label,
    Operator = h.operator,
    Keyword = h.keyword,
    Exception = h.control,
    PreProc = h.special,
    Include = h.control_import,
    Define = h.func_macro,
    Macro = h.func_macro,
    PreCondit = h.control,
    Type = h.type,
    StorageClass = h.storage_modifier,
    Structure = h.namespace,
    Typedef = h.type,
    Special = h.special,
    SpecialChar = h.special,
    Tag = h.tag,
    Delimiter = h.punctuation,
    Debug = h.special,
    Underlined = h.link_url,
    Ignore = { fg = p.t3 },
    Error = h.error,
    Todo = { fg = p.t1, bg = p.warning, bold = true },

    -- Tree-sitter groups
    ["@comment"] = h.comment,
    ["@comment.documentation"] = h.comment_doc,
    ["@comment.error"] = h.error,
    ["@comment.warning"] = h.warning,
    ["@comment.todo"] = { fg = p.t1, bg = p.warning, bold = true },
    ["@comment.note"] = h.info,

    ["@constant"] = h.constant,
    ["@constant.builtin"] = h.constant,
    ["@constant.macro"] = h.func_macro,
    ["@constant.character"] = h.constant,
    ["@constant.character.escape"] = h.special,
    ["@constant.numeric.integer"] = h.constant,
    ["@constant.numeric.float"] = h.constant,
    ["@constant.builtin.boolean"] = h.constant,
    ["@module"] = h.namespace,
    ["@module.builtin"] = h.namespace,
    ["@label"] = h.label,

    ["@string"] = h.string,
    ["@string.documentation"] = h.comment_doc,
    ["@string.regexp"] = h.regexp,
    ["@string.escape"] = h.special,
    ["@string.special"] = h.special,
    ["@string.special.symbol"] = h.constant,
    ["@string.special.path"] = h.link_text,
    ["@character"] = h.string,
    ["@character.special"] = h.special,

    ["@boolean"] = h.constant,
    ["@number"] = h.constant,
    ["@number.float"] = h.constant,

    ["@type"] = h.type,
    ["@type.builtin"] = h.type,
    ["@type.definition"] = h.type,
    ["@attribute"] = h.special,
    ["@attribute.builtin"] = h.special,
    ["@property"] = h.member,

    ["@function"] = h.func,
    ["@function.builtin"] = h.func,
    ["@function.call"] = h.func,
    ["@function.macro"] = h.func_macro,
    ["@function.method"] = h.method,
    ["@function.method.call"] = h.method,
    ["@constructor"] = h.type,
    ["@operator"] = h.operator,

    ["@keyword"] = h.keyword,
    ["@keyword.function"] = h.keyword_function,
    ["@keyword.operator"] = h.operator,
    ["@keyword.import"] = h.control_import,
    ["@keyword.type"] = h.type,
    ["@keyword.modifier"] = h.storage_modifier,
    ["@keyword.repeat"] = h.control,
    ["@keyword.return"] = h.control,
    ["@keyword.conditional"] = h.control,
    ["@keyword.exception"] = h.control,
    ["@keyword.debug"] = h.special,
    ["@keyword.directive"] = h.special,

    ["@punctuation"] = h.punctuation,
    ["@punctuation.delimiter"] = h.punctuation,
    ["@punctuation.bracket"] = h.punctuation,
    ["@punctuation.special"] = h.punctuation,

    ["@variable"] = h.variable,
    ["@variable.builtin"] = h.variable,
    ["@variable.parameter"] = h.parameter,
    ["@variable.parameter.builtin"] = h.parameter,
    ["@variable.member"] = h.member,
    ["@variable.other.member"] = h.member,

    -- Helix-style capture aliases used by some queries and extensions.
    ["@comment.line"] = h.comment,
    ["@comment.block.documentation"] = h.comment_doc,
    ["@keyword.control.import"] = h.control_import,
    ["@keyword.control.return"] = h.control,
    ["@keyword.control.conditional"] = h.control,
    ["@keyword.control.repeat"] = h.control,
    ["@keyword.control.exception"] = h.control,
    ["@keyword.storage.type"] = h.keyword,
    ["@keyword.storage.modifier"] = h.storage_modifier,

    ["@markup.heading"] = h.heading,
    ["@markup.heading.1"] = h.heading,
    ["@markup.heading.2"] = h.heading,
    ["@markup.heading.3"] = h.heading,
    ["@markup.heading.4"] = h.heading,
    ["@markup.heading.5"] = h.heading,
    ["@markup.heading.6"] = h.heading,
    ["@markup.list"] = h.list,
    ["@markup.raw"] = h.raw,
    ["@markup.raw.block"] = h.raw,
    ["@markup.link"] = h.link_text,
    ["@markup.link.label"] = h.link_text,
    ["@markup.link.url"] = h.link_url,
    ["@markup.strong"] = h.markup,
    ["@markup.italic"] = h.markup,
    ["@markup.strikethrough"] = h.strikethrough,
    ["@markup.quote"] = h.quote,
    ["@markup.math"] = h.special,

    ["@tag"] = h.tag,
    ["@tag.attribute"] = h.member,
    ["@tag.delimiter"] = h.punctuation,

    -- Built-in diagnostics and health reporting
    DiagnosticError = h.error,
    DiagnosticWarn = h.warning,
    DiagnosticInfo = h.info,
    DiagnosticHint = h.hint,
    DiagnosticOk = { fg = p.diff_plus, bold = true },
    DiagnosticVirtualTextError = h.error,
    DiagnosticVirtualTextWarn = h.warning,
    DiagnosticVirtualTextInfo = h.info,
    DiagnosticVirtualTextHint = h.hint,
    DiagnosticUnderlineError = h.diagnostic_error,
    DiagnosticUnderlineWarn = h.diagnostic_warning,
    DiagnosticUnderlineInfo = h.diagnostic_info,
    DiagnosticUnderlineHint = h.diagnostic_hint,
    DiagnosticFloatingError = h.error,
    DiagnosticFloatingWarn = h.warning,
    DiagnosticFloatingInfo = h.info,
    DiagnosticFloatingHint = h.hint,
    DiagnosticSignError = h.error,
    DiagnosticSignWarn = h.warning,
    DiagnosticSignInfo = h.info,
    DiagnosticSignHint = h.hint,
    HealthError = h.error,
    HealthSuccess = { fg = p.diff_plus, bold = true },
    HealthWarning = h.warning,

    -- Diff and git signs
    diffAdded = h.diff_add,
    diffRemoved = h.diff_delete,
    diffChanged = h.diff_change,
    diffOldFile = h.diff_delete,
    diffNewFile = h.diff_add,
    diffFile = h.link_text,
    diffLine = h.member,
    diffIndexLine = h.quote,

    GitSignsAdd = { fg = p.t8 },
    GitSignsChange = { fg = p.t11 },
    GitSignsDelete = { fg = p.t7 },
    GitSignsTopdelete = { fg = p.t7 },
    GitSignsChangedelete = { fg = p.t11 },
    GitSignsUntracked = { fg = p.t6 },
    GitSignsAddNr = { fg = p.t8 },
    GitSignsChangeNr = { fg = p.t11 },
    GitSignsDeleteNr = { fg = p.t7 },
    GitSignsTopdeleteNr = { fg = p.t7 },
    GitSignsChangedeleteNr = { fg = p.t11 },
    GitSignsUntrackedNr = { fg = p.t6 },
    GitSignsAddCul = { fg = p.t8 },
    GitSignsChangeCul = { fg = p.t11 },
    GitSignsDeleteCul = { fg = p.t7 },
    GitSignsTopdeleteCul = { fg = p.t7 },
    GitSignsChangedeleteCul = { fg = p.t11 },
    GitSignsUntrackedCul = { fg = p.t6 },
    GitSignsAddLn = { bg = bg(p.comment_doc, transparent) },
    GitSignsChangeLn = { bg = bg(p.ruler, transparent) },
    GitSignsDeleteLn = { bg = bg(p.comment, transparent) },
    GitSignsTopdeleteLn = { bg = bg(p.comment, transparent) },
    GitSignsChangedeleteLn = { bg = bg(p.ruler, transparent) },
    GitSignsUntrackedLn = { bg = bg(p.comment_doc, transparent) },
    GitSignsStagedAdd = { fg = p.t5 },
    GitSignsStagedChange = { fg = p.t5 },
    GitSignsStagedDelete = { fg = p.t3 },
    GitSignsStagedTopdelete = { fg = p.t3 },
    GitSignsStagedChangedelete = { fg = p.t5 },
    GitSignsStagedUntracked = { fg = p.t5 },
    GitSignsAddPreview = { fg = p.t8, bg = bg(p.comment_doc, transparent) },
    GitSignsDeletePreview = { fg = p.t7, bg = bg(p.comment, transparent) },
    GitSignsAddInline = { bg = bg(p.comment_doc, transparent) },
    GitSignsChangeInline = { bg = bg(p.ruler, transparent) },
    GitSignsDeleteInline = { bg = bg(p.comment, transparent) },
    GitSignsAddLnInline = { bg = bg(p.comment_doc, transparent) },
    GitSignsChangeLnInline = { bg = bg(p.ruler, transparent) },
    GitSignsDeleteLnInline = { bg = bg(p.comment, transparent) },
    GitSignsDeleteVirtLn = { fg = p.t7, bg = bg(p.comment, transparent) },
    GitSignsDeleteVirtLnInLine = { bg = bg(p.comment, transparent) },
    GitSignsVirtLnum = { fg = p.t7 },
    GitSignsCurrentLineBlame = { fg = p.t5, italic = true },

    -- LSP references, inlay hints, and semantic token groups
    LspReferenceText = { bg = p.ruler },
    LspReferenceRead = { bg = p.ruler },
    LspReferenceWrite = { bg = p.ruler, bold = true },
    LspCodeLens = h.comment,
    LspCodeLensSeparator = h.comment,
    LspSignatureActiveParameter = h.parameter,
    LspInlayHint = h.inlay_hint,

    ["@lsp.type.class"] = h.type,
    ["@lsp.type.comment"] = h.comment,
    ["@lsp.type.decorator"] = h.special,
    ["@lsp.type.enum"] = h.type,
    ["@lsp.type.enumMember"] = h.constant,
    ["@lsp.type.event"] = h.type,
    ["@lsp.type.function"] = h.func,
    ["@lsp.type.interface"] = h.type,
    ["@lsp.type.keyword"] = h.keyword,
    ["@lsp.type.macro"] = h.func_macro,
    ["@lsp.type.method"] = h.method,
    ["@lsp.type.modifier"] = h.storage_modifier,
    ["@lsp.type.namespace"] = h.namespace,
    ["@lsp.type.number"] = h.constant,
    ["@lsp.type.operator"] = h.operator,
    ["@lsp.type.parameter"] = h.parameter,
    ["@lsp.type.property"] = h.member,
    ["@lsp.type.regexp"] = h.regexp,
    ["@lsp.type.string"] = h.string,
    ["@lsp.type.struct"] = h.type,
    ["@lsp.type.type"] = h.type,
    ["@lsp.type.typeParameter"] = h.type,
    ["@lsp.type.variable"] = h.variable,

    -- Common plugin surfaces
    TelescopeNormal = h.popup,
    TelescopeBorder = extend(h.window, { bg = bg(p.t1, transparent) }),
    TelescopeTitle = h.text_focus,
    TelescopePromptNormal = h.menu,
    TelescopePromptBorder = extend(h.window, { bg = bg(p.t1, transparent) }),
    TelescopePromptTitle = h.text_focus,
    TelescopePromptPrefix = h.keyword_function,
    TelescopeMatching = h.jump_label,
    TelescopeSelection = h.selection,
    TelescopeSelectionCaret = h.jump_label,
    TelescopeMultiSelection = h.list,

    WhichKey = h.jump_label,
    WhichKeyGroup = h.keyword,
    WhichKeyDesc = h.text,
    WhichKeySeparator = h.separator,
    WhichKeyValue = h.comment,

    IblIndent = h.indent_guide,
    IblScope = h.text_focus,
    IndentBlanklineChar = h.indent_guide,
    IndentBlanklineContextChar = h.text_focus,

    MiniIndentscopeSymbol = h.text_focus,
    MiniCursorword = { bg = p.ruler },
    MiniCursorwordCurrent = { bg = p.ruler },
    MiniStatuslineModeNormal = h.statusline_normal,
    MiniStatuslineModeInsert = h.statusline_insert,
    MiniStatuslineModeVisual = h.statusline_select,
    MiniStatuslineModeReplace = h.statusline_select,
    MiniStatuslineModeCommand = h.statusline_normal,
    MiniStatuslineModeOther = h.statusline_normal,
    MiniStarterHeader = h.heading,
    MiniStarterItem = h.text,
    MiniStarterFooter = h.comment,
    MiniTablineCurrent = h.bufferline_active,
    MiniTablineVisible = h.bufferline,
    MiniTablineHidden = h.bufferline,
    MiniTablineFill = { bg = p.t1 },

    CmpItemAbbr = h.text,
    CmpItemAbbrMatch = h.jump_label,
    CmpItemAbbrMatchFuzzy = h.jump_label,
    CmpItemMenu = h.comment,
    CmpItemKind = h.special,
    CmpItemKindFunction = h.func,
    CmpItemKindMethod = h.method,
    CmpItemKindVariable = h.variable,
    CmpItemKindField = h.member,
    CmpItemKindProperty = h.member,
    CmpItemKindKeyword = h.keyword,
    CmpItemKindClass = h.type,
    CmpItemKindInterface = h.type,
    CmpItemKindText = h.text,
    CmpItemKindSnippet = h.special,

    BlinkCmpMenu = h.menu,
    BlinkCmpMenuBorder = extend(h.window, { bg = bg(p.t1, transparent) }),
    BlinkCmpLabel = h.text,
    BlinkCmpLabelMatch = h.jump_label,
    BlinkCmpDoc = h.popup,
    BlinkCmpDocBorder = extend(h.window, { bg = bg(p.t1, transparent) }),
    BlinkCmpSignatureHelp = h.popup,
    BlinkCmpSignatureHelpBorder = extend(h.window, { bg = bg(p.t1, transparent) }),

    HopNextKey = h.jump_label,
    HopNextKey1 = h.jump_label,
    HopNextKey2 = { fg = p.highlight_three, bold = true },
    HopUnmatched = h.comment,
    LeapLabelPrimary = h.jump_label,
    LeapLabelSecondary = { fg = p.highlight_three, bold = true },
    LeapMatch = { fg = p.t2, bg = p.highlight_two, bold = true },
    FlashBackdrop = h.comment,
    FlashMatch = { fg = p.selection_fg, bg = p.selection },
    FlashCurrent = { fg = p.t2, bg = p.highlight },
    FlashLabel = { fg = p.t1, bg = p.highlight_three, bold = true },
    FlashPrompt = h.statusline,
    FlashPromptIcon = h.special,
    FlashCursor = h.cursor_normal,

    NvimTreeNormal = h.background,
    NvimTreeNormalNC = h.background,
    NvimTreeRootFolder = h.namespace,
    NvimTreeFolderName = h.text,
    NvimTreeFolderIcon = h.tag,
    NvimTreeOpenedFolderName = h.text_focus,
    NvimTreeEmptyFolderName = h.comment,
    NvimTreeIndentMarker = h.indent_guide,
    NvimTreeGitDirty = h.diff_change,
    NvimTreeGitNew = h.diff_add,
    NvimTreeGitDeleted = h.diff_delete,
    NvimTreeSpecialFile = h.link_text,
    NvimTreeImageFile = h.string,
    NvimTreeOpenedFile = h.selection,
    NvimTreeWinSeparator = h.separator,

    NeoTreeBufferNumber = h.constant,
    NeoTreeCursorLine = extend(h.cursorline, { fg = p.t10 }),
    NeoTreeDimText = h.comment,
    NeoTreeDirectoryIcon = h.control_import,
    NeoTreeDirectoryName = extend(h.control_import, { bold = true }),
    NeoTreeDotfile = h.comment,
    NeoTreeFadeText1 = { fg = p.t5 },
    NeoTreeFadeText2 = { fg = p.t3 },
    NeoTreeFileIcon = { fg = p.t5 },
    NeoTreeFileName = { fg = p.t10 },
    NeoTreeFileNameOpened = { fg = p.t10, bold = true },
    NeoTreeFileStats = h.member,
    NeoTreeFileStatsHeader = h.comment,
    NeoTreeFilterTerm = h.jump_label,
    NeoTreeFloatBorder = extend(h.window, { bg = bg(p.t1, transparent) }),
    NeoTreeFloatNormal = h.popup,
    NeoTreeFloatTitle = h.text_focus,
    NeoTreeGitAdded = { fg = p.t8 },
    NeoTreeGitConflict = h.error,
    NeoTreeGitDeleted = h.diff_delete,
    NeoTreeGitIgnored = h.comment,
    NeoTreeGitModified = { fg = p.t6 },
    NeoTreeGitRenamed = { fg = p.t9 },
    NeoTreeGitStaged = { fg = p.t8 },
    NeoTreeGitUntracked = { fg = p.t9 },
    NeoTreeGitUnstaged = { fg = p.t5 },
    NeoTreeHiddenByName = h.comment,
    NeoTreeIgnored = h.comment,
    NeoTreeIndentMarker = h.indent_guide,
    NeoTreeMessage = h.quote,
    NeoTreeModified = { fg = p.t8 },
    NeoTreeNormal = extend(h.background, { fg = p.t10 }),
    NeoTreeNormalNC = extend(h.background, { fg = p.t10 }),
    NeoTreeSignColumn = extend(h.gutter, { bg = bg(p.t2, transparent) }),
    NeoTreeStatusLine = { fg = p.t10, bg = bg(p.ruler, transparent) },
    NeoTreeStatusLineNC = { fg = p.t5, bg = bg(p.t2, transparent) },
    NeoTreeTabActive = h.bufferline_active,
    NeoTreeTabInactive = h.bufferline,
    NeoTreeTabSeparatorActive = h.separator,
    NeoTreeTabSeparatorInactive = h.separator,
    NeoTreeVertSplit = extend(h.separator, { bg = bg(p.t2, transparent) }),
    NeoTreeWinSeparator = extend(h.separator, { bg = bg(p.t2, transparent) }),
    NeoTreeEndOfBuffer = { fg = p.t2, bg = bg(p.t2, transparent) },
    NeoTreeRootName = extend(h.control_import, { bold = true }),
    NeoTreeSymbolicLinkTarget = h.link_text,
    NeoTreeTitleBar = { fg = p.t10, bg = bg(p.ruler, transparent), bold = true },
    NeoTreeExpander = h.indent_guide,
    NeoTreeWindowsHidden = h.comment,
    NeoTreePreview = h.popup,

    HarpoonWindow = h.popup,
    HarpoonInactive = h.bufferline,
    HarpoonActive = h.bufferline_active,
    HarpoonNumberActive = h.jump_label,
    HarpoonNumberInactive = h.member,

    LazyGitFloat = { fg = p.t10, bg = bg(p.t1, transparent) },
    LazyGitBorder = { fg = p.t6, bg = bg(p.t1, transparent) },
    LazyGitTitle = { fg = p.highlight_three, bg = bg(p.t1, transparent), bold = true },
    LazyGitHeader = h.text_focus,
    LazyGitCurrentFile = h.keyword_function,
    LazyGitPath = h.member,
    LazyGitBranch = h.namespace,
    LazyGitSelectedLine = h.selection,
    LazyGitStagedChanges = h.diff_add,
    LazyGitUnstagedChanges = h.warning,
    LazyGitUntrackedFiles = h.diff_add,
    LazyGitDiffAdd = h.diff_add,
    LazyGitDiffChange = h.diff_change,
    LazyGitDiffDelete = h.diff_delete,

    SupermavenSuggestion = h.inlay_hint,

    ["99RuleRef"] = h.jump_label,
    ["99FileRef"] = h.keyword_function,

    FzfLuaNormal = { fg = p.t10, bg = bg(p.t2, transparent) },
    FzfLuaBorder = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaTitle = { fg = p.highlight_three, bg = bg(p.t2, transparent), bold = true },
    FzfLuaTitleFlags = { fg = p.highlight, bg = bg(p.t2, transparent), bold = true },
    FzfLuaBackdrop = { bg = p.black },
    FzfLuaHelpNormal = { fg = p.t10, bg = bg(p.t2, transparent) },
    FzfLuaHelpBorder = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaPreviewNormal = { fg = p.t10, bg = bg(p.t2, transparent) },
    FzfLuaPreviewBorder = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaPreviewTitle = { fg = p.highlight_three, bg = bg(p.t2, transparent), bold = true },
    FzfLuaCursor = h.cursor_normal,
    FzfLuaCursorLine = h.cursorline,
    FzfLuaCursorLineNr = h.line_nr_selected,
    FzfLuaSearch = { fg = p.t2, bg = p.highlight },
    FzfLuaScrollBorderEmpty = { fg = p.t2, bg = bg(p.t2, transparent) },
    FzfLuaScrollBorderFull = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaScrollFloatEmpty = { bg = bg(p.t2, transparent) },
    FzfLuaScrollFloatFull = { bg = bg(p.t3, transparent) },
    FzfLuaDirIcon = h.tag,
    FzfLuaDirPart = { fg = p.t6, bg = bg(p.t2, transparent) },
    FzfLuaFilePart = { fg = p.t10, bg = bg(p.t2, transparent) },
    FzfLuaHeaderBind = h.jump_label,
    FzfLuaHeaderText = { fg = p.t5, bg = bg(p.t2, transparent) },
    FzfLuaPathColNr = h.member,
    FzfLuaPathLineNr = h.constant,
    FzfLuaLivePrompt = h.keyword_function,
    FzfLuaLiveSym = h.jump_label,
    FzfLuaBufId = h.bufferline,
    FzfLuaBufName = h.text,
    FzfLuaBufLineNr = h.member,
    FzfLuaBufNr = h.constant,
    FzfLuaBufFlagCur = h.jump_label,
    FzfLuaBufFlagAlt = h.keyword,
    FzfLuaTabTitle = h.jump_label,
    FzfLuaTabMarker = h.keyword_function,
    FzfLuaCmdEx = h.control,
    FzfLuaCmdBuf = h.diff_add,
    FzfLuaCmdGlobal = h.namespace,
    FzfLuaFzfNormal = { fg = p.t10, bg = bg(p.t2, transparent) },
    FzfLuaFzfCursorLine = h.cursorline,
    FzfLuaFzfMatch = h.jump_label,
    FzfLuaFzfBorder = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaFzfScrollbar = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaFzfSeparator = { fg = p.t3, bg = bg(p.t2, transparent) },
    FzfLuaFzfGutter = { fg = p.t10, bg = bg(p.t2, transparent) },
    FzfLuaFzfHeader = { fg = p.t5, bg = bg(p.t2, transparent) },
    FzfLuaFzfInfo = { fg = p.t5, bg = bg(p.t2, transparent) },
    FzfLuaFzfPointer = h.jump_label,
    FzfLuaFzfMarker = h.jump_label,
    FzfLuaFzfSpinner = h.keyword_function,
    FzfLuaFzfPrompt = h.keyword_function,
    FzfLuaFzfQuery = { fg = p.t10, bg = bg(p.t2, transparent) },
  }
end

-- Populate the terminal palette so :terminal and embedded terminals stay close
-- to the scheme instead of falling back to unrelated default ANSI colors.
function M.apply_terminal()
  local p = palette
  vim.g.terminal_color_0 = p.t1
  vim.g.terminal_color_1 = p.t7
  vim.g.terminal_color_2 = p.diff_plus
  vim.g.terminal_color_3 = p.highlight_two
  vim.g.terminal_color_4 = p.display
  vim.g.terminal_color_5 = p.highlight
  vim.g.terminal_color_6 = p.selection
  vim.g.terminal_color_7 = p.t10
  vim.g.terminal_color_8 = p.t3
  vim.g.terminal_color_9 = p.error
  vim.g.terminal_color_10 = p.diff_plus
  vim.g.terminal_color_11 = p.warning
  vim.g.terminal_color_12 = p.diff_delta
  vim.g.terminal_color_13 = p.t11
  vim.g.terminal_color_14 = p.t8
  vim.g.terminal_color_15 = p.t9
end

function M.load()
  M.apply_terminal()

  -- Set every group explicitly to avoid depending on the user's current theme
  -- or plugin order.
  for group, spec in pairs(M.groups()) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

return M
